#!/bin/bash
# Claude Code Format Hook - Auto-generated by /setup-format-hook
# PostToolUse hook: runs Biome (formatter + linter) after Edit/Write/NotebookEdit
#
# Exit code rule: PostToolUse hook must always exit 0.
# - exit 2 surfaces as a "blocking error" in the UI and misleads the agent
#   into thinking the edit failed (GitHub Issue #19009).
# - Biome runs silently with `|| true`; residual lint errors will be picked up
#   by the agent on the next read.

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ] || [ ! -f "$FILE_PATH" ]; then
  exit 0
fi

# Biome lives in app/node_modules; only files inside the app/ subproject are
# covered by biome.json, so scope the hook to that subtree.
BIOME="$CLAUDE_PROJECT_DIR/app/node_modules/.bin/biome"

if [ ! -x "$BIOME" ]; then
  exit 0
fi

case "$FILE_PATH" in
  "$CLAUDE_PROJECT_DIR/app/"*) ;;
  *) exit 0 ;;
esac

EXT="${FILE_PATH##*.}"

case "$EXT" in
  js|jsx|ts|tsx|mjs|cjs|json|jsonc)
    "$BIOME" check --write "$FILE_PATH" 2>/dev/null || true
    ;;
esac

exit 0
